services:
  client:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - ./config.js:/app/config.js
      - ./mirasaki-music-bot.db:/app/mirasaki-music-bot.db